# BW \#176 Religious restrictions
Religion can inspire people to do all sorts of great things, on their own and in groups. But as we know all too well, it can also inspire them to do all sorts of bad things — both to members of their own religion with whom they disagree, and to followers of other religions, who are seen as wrong, heretical, or deserving of punishment.

Indeed, a large number of conflicts around the world, both now and over the history of humanity, can be seen through the lens of religious disagreements.

## Data and six questions
This week, we'll look at the state of affairs, now and over time, for various religions in countries around the world, using the Pew data.
The Pew data can be downloaded from https://www.pewresearch.org/dataset/dataset-global-restrictions-on-religion-2007-2022/ .

## Challenges
The learning goals include grouping, reshaping data, pivot tables, and plotting with Plotly.
- Read the main CSV file into a Pandas df. From the 2022 data, were any countries among the 10 highest GRI (Governmet restrictions index) and also the 10 highest SHI (Social hostilities index) based on religion ?
- Which 10 countries had the greatest improvement (i.e., lower score) in GRI from 2007 to 2022 ? Which 10 countries showed such improvements in the area of SHI ?

In [1]:
import pandas as pd

In [2]:
filename = r'C:\Users\npigeon1\Pandas-Bamboo-Weekly\BW #176 Religious restrictions\Global-Restrictions-on-Religion-2007-2022-Dataset\PublicDataset_ReligiousRestrictions_2007to2022.csv'

In [3]:
df = pd.read_csv(filename,
                 parse_dates=['Question_Year'])
df.columns

Index(['Nation_fk', 'Ctry_EditorialName', 'Region5', 'Question_Year', 'GRI',
       'SHI', 'GRI_Q_1', 'GRI_Q_2', 'GRI_Q_3', 'GRI_Q_4', 'GRI_Q_5', 'GRI_Q_6',
       'GRI_Q_7', 'GRI_Q_8', 'GRI_Q_9', 'GRI_Q_10', 'GRI_Q_11',
       'GRI_Q_11_Unaffiliated', 'GRI_Q_11_Christianity', 'GRI_Q_11_Islam',
       'GRI_Q_11_Buddhism', 'GRI_Q_11_Hinduism', 'GRI_Q_11_Judaism',
       'GRI_Q_11_Other_Religions', 'GRI_Q_11_Folk_Religions', 'GRI_Q_12',
       'GRI_Q_13', 'GRI_Q_14', 'GRI_Q_15', 'GRI_Q_16_Reasons', 'GRI_Q_16',
       'GRI_Q_17', 'GRI_Q_18', 'GRI_Q_19', 'GRI_Q_19_Extent',
       'GRI_Q_19_Property_Damage', 'GRI_Q_19_Detentions',
       'GRI_Q_19_Displacements', 'GRI_Q_19_Abuse', 'GRI_Q_19_Deaths',
       'GRI_Q_20_1', 'GRI_Q_20_2', 'GRI_Q_20_3_a', 'GRI_Q_20_3_b',
       'GRI_Q_20_3_c', 'GRI_Q_20_3', 'GRI_Q_20_4', 'GRI_Q_20_5',
       'GRX_22_Blasphemy', 'GRX_22_Apostasy', 'GRX_22_Hate_Speech',
       'GRX_22_Criticism_of_Religion', 'SHI_Q_1_Extent', 'SHI_Q_1_Harassment',
       'SHI_Q_1_Property_Damage', 'SHI_Q_1_Detentions',
       'SHI_Q_1_Displacements', 'SHI_Q_1_Assaults', 'SHI_Q_1_Deaths',
       'SHI_Q_1_Harass_Unaffiliated', 'SHI_Q_1_Harass_Christianity',
       'SHI_Q_1_Harass_Islam', 'SHI_Q_1_Harass_Buddhism',
       'SHI_Q_1_Harass_Hinduism', 'SHI_Q_1_Harass_Judaism',
       'SHI_Q_1_Harass_Other_Religions', 'SHI_Q_1_Harass_Folk_Religions',
       'SHI_Q_2', 'SHI_Q_3', 'SHI_Q_4', 'SHI_Q_4_Extent', 'SHI_Q_5',
       'SHI_Q_5_Extent', 'SHI_Q_6', 'SHI_Q_7', 'SHI_Q_8', 'SHI_Q_9',
       'SHI_Q_10', 'SHI_Q_11', 'SHI_Q_12', 'SHI_Q_13'],
      dtype='object')

In [4]:
highest_gri=df[df['Question_Year'].dt.year == 2022][['Ctry_EditorialName', 'GRI']].nlargest(10, 'GRI')
highest_gri

     Ctry_EditorialName    GRI
575               China  9.085
799               Egypt  8.370
15          Afghanistan  8.220
1263               Iran  8.200
2747              Syria  7.895
1247          Indonesia  7.855
2319             Russia  7.660
175          Azerbaijan  7.485
47              Algeria  7.455
1695           Malaysia  7.305

This shows that the most restrictive government regarding religion is China, followed by Egypt, Afghanistan, Iran, and Syria

What if we look not at government policy, but at hostility to religion (or more precisely, to members of one or more particular religions) among the population, rather than as part of government policy? We can run the same query, just substituting SHI for GRI:

In [5]:
highest_shi=df[df['Question_Year'].dt.year == 2022][['Ctry_EditorialName', 'SHI']].nlargest(10, ['SHI'])
highest_shi

           Ctry_EditorialName     SHI
1231                    India  9.2923
2047                  Nigeria  8.7154
2747                    Syria  8.0769
2111                 Pakistan  7.8846
1279                     Iraq  7.8231
799                     Egypt  7.3692
15                Afghanistan  7.3077
1311                   Israel  7.1154
1583                    Libya  6.4769
2143  Palestinian territories  6.2846

A different picture emerges here: China is nowhere to be found, but at the top of the list are India and Nigeria.

My question was whether any countries are on both of these lists, with high government restrictions on religion and also high levels of social tension and hostility among the population.

In [6]:
set(highest_gri['Ctry_EditorialName']) & set(highest_shi['Ctry_EditorialName'])

{'Afghanistan', 'Egypt', 'Syria'}

In [7]:
highest_gri.set_index('Ctry_EditorialName').index.intersection(highest_shi.set_index('Ctry_EditorialName').index)

Index(['Egypt', 'Afghanistan', 'Syria'], dtype='object', name='Ctry_EditorialName')

### Which 10 countries had the greatest improvement (i.e., lower score) in GRI from 2007 to 2022 ? Which 10 countries showed such improvements in the area of SHI ?
On cherche les 10 pays dont le score a le plus baissé entre les deux dates (2007 → 2022).

In [8]:
df.head()

,Nation_fk,Ctry_EditorialName,Region5,Question_Year,GRI,SHI,GRI_Q_1,GRI_Q_2,GRI_Q_3,GRI_Q_4,...,SHI_Q_5,SHI_Q_5_Extent,SHI_Q_6,SHI_Q_7,SHI_Q_8,SHI_Q_9,SHI_Q_10,SHI_Q_11,SHI_Q_12,SHI_Q_13
0,1,Afghanistan,Asia-Pacific,2007-01-01,5.320,8.46154,0.5,0.67,0.67,0.67,...,1,1.0,1.00,1.0,1,1,1,1,0.5,1.0
1,1,Afghanistan,Asia-Pacific,2008-01-01,5.275,7.82308,0.5,0.67,0.67,0.67,...,1,1.0,1.00,1.0,1,1,1,1,1.0,1.0
2,1,Afghanistan,Asia-Pacific,2009-01-01,6.520,8.59231,0.5,0.67,1.00,1.00,...,1,1.0,0.67,1.0,1,1,1,1,1.0,1.0
3,1,Afghanistan,Asia-Pacific,2010-01-01,7.955,7.69231,0.5,0.67,0.67,1.00,...,1,1.0,1.00,1.0,1,1,1,1,0.5,1.0
4,1,Afghanistan,Asia-Pacific,2011-01-01,8.020,7.43846,0.5,0.67,1.00,1.00,...,1,1.0,1.00,1.0,1,1,1,1,0.5,1.0

In [33]:
gri_afghanistan_2022 = df[(df['Ctry_EditorialName'] == 'Afghanistan') & (df['Question_Year'].dt.year == 2022)]['GRI'].mean()
gri_afghanistan_2022

np.float64(8.22)

In [34]:
gri_afghanistan_2007 = df[(df['Ctry_EditorialName'] == 'Afghanistan') & (df['Question_Year'].dt.year == 2007)]['GRI'].mean()
gri_afghanistan_2007

np.float64(5.32)

In [35]:
gri_afghanistan_2022 - gri_afghanistan_2007

np.float64(2.9000000000000004)

In [57]:
df_filtered = df[df['Question_Year'].dt.year.isin([2007, 2022])].groupby(['Ctry_EditorialName', 'Question_Year'])[['GRI']].mean().unstack()
df_filtered.columns = df_filtered.columns.droplevel(0)
df_filtered

Question_Year       2007-01-01  2022-01-01
Ctry_EditorialName
Afghanistan              5.320       8.220
Albania                  0.775       1.975
Algeria                  5.585       7.455
Andorra                  0.875       2.765
Angola                   3.285       4.130
...                        ...         ...
Vietnam                  6.550       6.670
Western Sahara           4.820       6.755
Yemen                    4.300       5.435
Zambia                   2.000       2.370
Zimbabwe                 2.850       3.155

[198 rows x 2 columns]

In [59]:
print(type(df_filtered.columns[0]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [62]:
df_filtered['improvement'] = df_filtered[pd.Timestamp('2007-01-01')] - df_filtered[pd.Timestamp('2022-01-01')]
df_filtered.sort_values(by='improvement', ascending=False).head(10)

Question_Year       2007-01-01 00:00:00  2022-01-01 00:00:00  improvement
Ctry_EditorialName
Monaco                            2.530                1.130        1.400
Comoros                           5.395                4.290        1.105
Saudi Arabia                      8.035                6.965        1.070
Belgium                           3.950                2.885        1.065
Sudan                             5.705                4.805        0.900
Gabon                             1.710                0.850        0.860
Turkmenistan                      5.575                4.770        0.805
Brunei                            7.205                6.470        0.735
Colombia                          1.820                1.085        0.735
Myanmar                           7.880                7.160        0.720

On commence par filtrer le df avec `loc` sur la colonne de Date puis on utilise la méthode `isin` pour garder uniquement les données entre 2007 et 2022

In [75]:
(
    df
    .assign(Year=df['Question_Year'].dt.year)
    .loc[lambda d: d['Year'].isin([2007, 2022]),
        ['Ctry_EditorialName', 'Year', 'SHI']]
    .pivot_table(index='Ctry_EditorialName', columns='Year', values='SHI', aggfunc='mean')
    .diff(axis='columns')
    [2022]
    .nsmallest(10)
    .round(2)
)

Ctry_EditorialName
Comoros          -5.64
Saudi Arabia     -5.07
Romania          -4.24
Ghana            -3.79
Timor-Leste      -3.78
Indonesia        -3.52
Greece           -3.34
Western Sahara   -3.27
Sudan            -3.02
Brunei           -3.02
Name: 2022, dtype: float64