# BW \#127 EU Comparisons
Compare European countries in a few ways. These statistics might not make for the most scintillating "in my country" conversations, but they will give you some additional perspective on how countries in Europe compare with one another.

## Data and six questions
This week's data comes from Eurostat (https://ec.europa.eu/eurostat/), which collects, analyzes, and publishes data on a wide variety of topics.

- Number of weekly hours worked: https://ec.europa.eu/eurostat/databrowser/view/lfsa_ewhun2/default/table
- Internet access: https://ec.europa.eu/eurostat/databrowser/view/isoc_ci_in_h/default/table

## Challenges
The learning goals include working with Excel files, window functions, filter and joins

- first let's look at how many weekly work hours people put in. Read from "Sheet 1" in the work file into a pandas df. Examine the file to see what values should be considered `NaN. Make the country-name column the index. Explain a reason why the EU data and euro-area might differ
- In 2024 (the most recent year of which we have data), which 5 countries worked the greatest and least number of hours ? Which five countries have most increased the number of hours worked (as a percentage) since 2015, and which have decreased ?

## Read from "Sheet 1" in the work file into a pandas df. Examine the file to see what values should be considered `NaN. Make the country-name column the index.

In [32]:
import pandas as pd

filename = r"C:\Users\npigeon1\Pandas-Bamboo-Weekly\BW #127 European comparisons\lfsa_ewhun2$defaultview_spreadsheet.xlsx"
df = pd.read_excel(filename, 
                   sheet_name="Sheet 1", # read sheet 1
                   skiprows=14, # skip the first 14 rows
                   nrows=38, # read only the first 39 rows
                   index_col=0, # use the first column as index
                   na_values=[':', 'not available'], # treat NaN values
                   header=None, # no header row
                   names = range(2015, 2025) # assign names to the remaining non index columns
                   )
df

c:\Users\npigeon1\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
European Union - 27 countries (from 2020),37.4,37.4,37.4,37.4,37.3,37.2,37.2,37.3,37.1,37.1
Euro area – 20 countries (from 2023),36.7,36.7,36.7,36.7,36.7,36.6,36.6,36.6,36.5,36.4
Belgium,37.1,37.1,37.6,37.3,37.3,37.3,36.7,36.7,36.4,36.2
Bulgaria,40.9,40.8,40.8,40.7,40.5,40.4,40.4,40.2,40.1,40.0
Czechia,40.7,40.6,40.4,40.4,40.3,40.2,39.7,39.8,39.6,39.4
Denmark,33.9,33.7,33.7,33.7,33.5,33.6,34.6,34.4,33.9,33.5
Germany,35.5,35.5,35.4,35.4,35.3,35.2,35.3,35.2,34.9,34.8
Estonia,39.0,38.8,38.8,38.6,38.4,38.2,38.0,37.8,37.7,37.8
Ireland,35.9,35.9,36.3,36.5,36.5,36.6,36.2,36.3,35.8,35.7
Greece,42.2,42.2,42.0,42.0,41.7,41.7,41.3,41.0,40.9,41.0
Spain,37.8,37.8,37.7,37.7,37.5,37.5,37.4,37.7,37.6,37.5
France,37.3,37.4,37.3,37.4,37.5,37.5,37.0,37.2,37.2,37.1
Croatia,39.8,39.6,39.8,39.7,39.9,39.8,39.7,39.6,39.8,39.6
Italy,37.1,37.0,37.2,37.3,37.2,37.0,37.3,37.3,37.4,37.2
Cyprus,39.6,39.3,39.4,39.4,39.5,39.3,39.0,39.4,39.8,39.9
Latvia,39.2,38.9,39.0,39.0,38.8,38.8,38.8,39.0,38.9,38.8
Lithuania,38.5,38.6,38.7,38.9,39.0,39.1,39.1,39.2,39.1,39.2
Luxembourg,37.5,37.5,37.4,37.7,37.9,37.5,38.1,38.0,37.9,37.8
Hungary,39.9,39.8,39.9,39.8,39.7,39.5,39.5,39.6,39.6,39.5
Malta,38.7,38.8,39.0,39.2,39.8,39.8,39.3,39.0,39.0,39.1
Netherlands,30.4,30.6,30.6,30.7,30.8,30.6,31.5,31.7,31.6,31.6
Austria,36.9,36.8,36.7,36.7,36.7,36.6,36.1,35.9,35.9,35.7
Poland,40.9,40.8,40.6,40.6,40.5,40.3,40.4,40.4,40.2,40.1
Portugal,40.1,39.9,40.0,40.0,39.9,39.7,39.9,39.9,39.8,39.7
Romania,40.0,40.0,39.9,39.8,40.0,39.9,40.2,40.2,40.1,40.0
Slovenia,39.4,39.5,39.3,39.4,39.6,39.6,39.6,39.5,39.4,39.4
Slovakia,40.3,40.1,39.9,40.1,40.2,40.0,39.6,39.6,39.6,39.5
Finland,37.2,37.0,37.1,37.2,37.0,36.9,35.9,35.7,35.7,35.9
Sweden,36.8,36.9,36.8,36.9,36.9,36.8,38.4,38.4,38.3,38.3
Iceland,39.8,39.5,39.3,39.4,39.3,38.6,38.3,38.2,38.3,38.1
Norway,33.9,34.0,34.1,34.0,33.9,33.9,34.4,34.5,34.5,34.7
Switzerland,35.4,35.3,35.3,35.3,35.2,35.2,36.1,36.1,36.1,36.0
United Kingdom,37.1,37.0,37.0,36.9,37.0,NaN,NaN,NaN,NaN,NaN
Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,41.6,41.8,41.9,41.7
Montenegro,43.7,43.4,43.3,44.2,44.5,44.4,NaN,NaN,NaN,NaN
North Macedonia,41.9,41.7,42.5,42.3,41.5,40.9,NaN,NaN,NaN,NaN
Serbia,43.6,43.4,43.0,43.0,42.8,42.7,43.1,43.0,42.6,42.2
Türkiye,47.6,47.0,46.6,45.9,45.6,44.7,45.3,45.1,45.0,44.2

let's examine the first two rows to compare EU and Euro. We observe that people in the Euro area globally work less hours than people in Europe as a whole.

In [48]:
df.iloc[0:2].T

,European Union - 27 countries (from 2020),Euro area – 20 countries (from 2023)
2015,37.4,36.7
2016,37.4,36.7
2017,37.4,36.7
2018,37.4,36.7
2019,37.3,36.7
2020,37.2,36.6
2021,37.2,36.6
2022,37.3,36.6
2023,37.1,36.5
2024,37.1,36.4

## In 2024 (the most recent year of which we have data), which 5 countries worked the greatest and least number of hours ? Which five countries have most increased the number of hours worked (as a percentage) since 2015, and which have decreased ?

In [52]:
df[2024].sort_values(ascending=False).head(5)  # Top 5 countries with most hours worked in 2024

Türkiye                   44.2
Serbia                    42.2
Bosnia and Herzegovina    41.7
Greece                    41.0
Poland                    40.1
Name: 2024, dtype: float64

In [53]:
df[2024].sort_values(ascending=True).head(5)  # Top 5 countries with least hours worked in 2024

Netherlands    31.6
Denmark        33.5
Norway         34.7
Germany        34.8
Ireland        35.7
Name: 2024, dtype: float64

Pour aller plus vite on peut utiliser les fonctions d'aggregations nlargest et nsmallest qui retournent respectivement les 5 plus grandes/ petites valeurs. On utilise agg pour les combiner.

In [ ]:
df[2024].agg(['nsmallest', 'nlargest'])

                        nsmallest  nlargest
Netherlands                  31.6       NaN
Denmark                      33.5       NaN
Norway                       34.7       NaN
Germany                      34.8       NaN
Ireland                      35.7       NaN
Türkiye                       NaN      44.2
Serbia                        NaN      42.2
Bosnia and Herzegovina        NaN      41.7
Greece                        NaN      41.0
Poland                        NaN      40.1

To know which countries have increased and decreased the most (as a percentage) from 2015 to 2024. We can apply similar logic there, but first we need to grab two columns (2015 and 2024), and apply the Pandas window function pct_change across the columns

In [57]:
df[[2015, 2024]].pct_change(axis='columns', fill_method=None)[2024].agg(['nsmallest', 'nlargest'])

             nsmallest  nlargest
Türkiye      -0.071429       NaN
Iceland      -0.042714       NaN
Finland      -0.034946       NaN
Austria      -0.032520       NaN
Serbia       -0.032110       NaN
Sweden             NaN  0.040761
Netherlands        NaN  0.039474
Norway             NaN  0.023599
Lithuania          NaN  0.018182
Switzerland        NaN  0.016949