# BW \#155 Gold
Lately the US dollars has been rather weak. This has made American goods, and anything else price in US dollars, cheaper than they were even a year ago.
But what does it mean for the dollar to be weak ? Mostly, that it takes less foreign currency than before to buy $1. 

There has been numerous articles about how much the price of gold has increased in the last year. It would be interesting to see that growth, to compare it with the change in the dollar's worth vs other currencies and also to look at central banks' holding of gold vs US dollar. 

## Data and six questions
This week's data comes from a several sources:
- https://stooq.com/q/d/?s=xauusd&ref=bambooweekly.com, the price of gold 
- https://stooq.com/q/d/?s=xagusd, price of silver 
- https://data.imf.org/en/datasets/IMF.STA:COFER, the proportion of US dollar that central banks own
- https://www.gold.org/goldhub/data/gold-reserves-by-country, at changes in the gold holdings at central banks

## Challenges
The learning goals include xcel files, dates and times, regular expressions, filtering, joins, grouping, plotting with plotly, and correlations.

- Read the historical gold prices into a data frame, treating the `Date` column as as `datetime` value, and making it the data frame's index. Create a line plot showing the price of gold throughout the data set. Create a second line plot showing only from 1925 through the present day. Then create a bar plot showing the percentage change in the mean price of gold for every 5-year period. How do the last 5 years compare with historical changes in gold's price? Use the `Close` column for these displays and calculations.
- Read in silver prices. Create a scatterplot comparing gold and silver prices, including a trendline. Use the `corr` method to see how correlated they are. What does the scatterplot tell you about the current relationship between gold and silver vs. their historical correlation?

In [9]:
import pandas as pd
from plotly import express as px

In [7]:
gold_df = pd.read_csv(r'C:\Users\npigeon1\Pandas-Bamboo-Weekly\BW #155 Gold\xauusd_d.csv',
                      parse_dates=['Date'],
                      index_col='Date')
gold_df

                Open      High       Low     Close
Date
1793-03-01    19.390    19.390    19.390    19.390
1793-06-01    19.390    19.390    19.390    19.390
1793-09-01    19.390    19.390    19.390    19.390
1793-12-01    19.390    19.390    19.390    19.390
1794-03-01    19.390    19.390    19.390    19.390
...              ...       ...       ...       ...
2026-02-18  4876.635  5010.855  4854.785  4977.445
2026-02-19  4977.765  5022.175  4960.895  4996.325
2026-02-20  4998.745  5097.795  4981.965  5097.435
2026-02-23  5109.800  5237.315  5097.435  5227.605
2026-02-24  5227.075  5249.495  5095.085  5142.855

[15188 rows x 4 columns]

In [10]:
(
    gold_df.pipe(px.line, y='Close')
)

In [19]:
(
    gold_df
    ['1925':]
    .pipe(px.line, y='Close')
)

In [8]:
silver_df = pd.read_csv(r'C:\Users\npigeon1\Pandas-Bamboo-Weekly\BW #155 Gold\xagusd_d.csv',
                      parse_dates=['Date'],
                      index_col='Date')
silver_df

               Open    High      Low   Close
Date
1792-03-01   1.2900   1.290   1.2900   1.290
1792-06-01   1.2900   1.290   1.2900   1.290
1792-09-01   1.2900   1.290   1.2900   1.290
1792-12-01   1.2900   1.290   1.2900   1.290
1793-03-01   1.2900   1.290   1.2900   1.290
...             ...     ...      ...     ...
2026-02-18  73.2835  78.336  72.3440  77.191
2026-02-19  77.3565  79.479  76.4930  78.533
2026-02-20  78.6875  84.615  77.5160  84.542
2026-02-23  85.0925  89.045  84.5420  88.205
2026-02-24  88.1170  88.919  85.0165  87.704

[16554 rows x 4 columns]